// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pigzupruhmsxefxzcfiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZ3p1cHJ1aG1zeGVmeHpjZml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTUyNDEsImV4cCI6MjA2NDI3MTI0MX0.z0o5w1JnXJLjjzHSeoX0nLQD0LSvcqr3a9JBYjA2ySI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);